isamplesorg/metadata

examples/SESAR/test/iSamplesIEEJR000MBasic.json
isamples_metadata/SESARTransformer.py
isamples_metadata/Transformer.py
tests/test_category_mapping.py

Full discussion in
https://github.com/isamplesorg/metadata/issues/22
~~@datadavev any concerns with how I'm planning on modeling the categories as enums?  That's how they're modeled in @smrgeoinfo's model, just unclear whether that's correct for Python.~~

Prep work for finalizing SESAR metadata categories:

---

isamples_metadata/SESARTransformer.py
isamples_metadata/Transformer.py
tests/test_elevation_values.py

Noticed that the elevation values were in feet as well as meters, make sure we handle both and test accordingly

Solr fixes

---

isamples_metadata/SESARTransformer.py
isamples_metadata/Transformer.py

These were crashers we hit when running the solr importer

Couple bug fixes found when running the solr importer

---

isamples_metadata/SESARTransformer.py

Made a mistake when fixing a merge conflict -- going to manually merge this one.  cc @datadavev

Fix failed merge

---

isamples_metadata/SESARTransformer.py
isamples_metadata/Transformer.py
tests/test_category_mapping.py

PyCharm and Black had some suggestions on how to make this better Python.  Get this integrated before we add to the badness with GEOME work.

Clean up warnings/formatting issues 

---

isamples_metadata/GEOMETransformer.py
isamples_metadata/SESARTransformer.py
pyproject.toml
tests/test_isamples_metadata.py

GEOME Child records are a mix of parent and child-specific information and need their own transformer.

GEOME Child Records

---

pyproject.toml

Bump the project version so ISB sees the new things.

Bump project version for dependency management in ISB

---

isamples_metadata/SESARTransformer.py
pyproject.toml

https://github.com//issues/59
I broke this during the OpenContext work.  Simple fix to get things transforming again.
@datadavev FYI

Fix sesar transformer

---

isamples_metadata/GEOMETransformer.py
isamples_metadata/OpenContextTransformer.py
isamples_metadata/SESARTransformer.py
isamples_metadata/SmithsonianTransformer.py
isamples_metadata/Transformer.py
pyproject.toml
tests/test_isamples_metadata.py

Add support for retrieving the last updated date when it is available in a source collection

Last updated timestamps

---

isamples_metadata/SESARTransformer.py

Part of the fix for https://github.com/isamplesorg/isamples_inabox/issues/52

IGSN should be uppercased, 

---

isamples_metadata/GEOMETransformer.py
pyproject.toml
tests/test_isamples_metadata.py

Backing support for https://github.com/isamplesorg/isamples_inabox/issues/68

Support for picking the proper transformer based on the identifier used to look up a record

---

src/vocabularies/materialType.ttl
src/vocabularies/sampledFeature.ttl
src/vocabularies/specimenType.ttl

rdfs:comment to skos:definition
minor updates in definitions
fix typo in glacierenvironment URI
add skos match relations to URIs from other vocabs.  Couldn't find matches for some concepts. Used closeMatch, narrowMatch (mapping to narrower concepts in target vocab), broadMatch (target concept broader than ours), related, and relatedMatch (when target concept definition is too different to be 'close')

SMR Vocabulary updates

---

src/vocabularies/materialSampleType.ttl
src/vocabularies/materialType.ttl
src/vocabularies/sampledFeature.ttl

address issues #110, #109, #108, #107.

Vocab updates

---

src/vocabularies/extensions/OpenContextMaterial.ttl
src/vocabularies/extensions/rockSedimentExtension.ttl

not sure we'll actually use this extension, but some updates based on analysis of OC metadata corpus
add fiber material
remove faience (not a material)
change plaster to plasterormortar

updates in OpenContext materials

---

README.md

I added badges for the 4 NSF grants supporting iSamples.

add NSF funding badges.

---

src/vocabularies/OpenContextMaterialSampleType.ttl
src/vocabularies/extensions/biologicEntityExtension.ttl

draft extensions for open context materials and biological entities as sampled feature types, subclass from biological entity

Vocab extensions

---

src/schemas/iSamplesSchemaBasic1.0.json
src/schemas/isamples_core.yaml

uses same property definition as in 137 and 138.  Addresses #134

add identifier property definition and make property of samplingEvent

---

src/schemas/iSamplesSchemaBasic1.0.json
src/schemas/isamples_core.yaml

bring in identifier defnition from 137 branch. Addresses issue #138

implement Agent object, use as range for registrant and responsibility

---

.github/workflows/build-docs.yml
Makefile
src/schemas/isamples_core.yaml

@datadavev These are the changes to run the vocabulary markdown generation directly from the vocabularies repo via the GitHub Action.  Note that I haven't seen it run successfully, but develop fails the same way as my branch does.

Convert doc generation vocabularies action

---

src/schemas/isamples_core.yaml

add property and property definition. address #154

add  obfuscated property on GeospatialCoordLocation

---

src/schemas/isamples_core.yaml

also remove carriage returns in descriptions for consistency. Address #151

add identifier and is_part_of on SamplingSite.

---

src/schemas/isamples_core.yaml

add dc_rights property on PhysicalSampleRecord

---

src/schemas/iSamplesSchemaCore1.0.json
src/schemas/isamples_core.yaml

This is a redo of https://github.com/isamplesorg/metadata/pull/171
Which had the wrong target branch when it was merged (due to being cut from another branch)

update yaml and json schema to generalize date formats

---

README.md

correct name for yaml schema,  material sample object type

---

requirements.txt

Action failed trying to get nbclient 0.7.1

nbclient==0.7.4, was nbclient==0.7.1
